# Generated by Django 5.2.10 on 2026-01-22 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='sudent_id',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
    ]
