# Generated by Django 5.2.10 on 2026-01-13 05:21

import issue.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='return_date',
            field=models.DateField(default=issue.models.seven_days_hence),
        ),
    ]
